swear('4r5e').
swear('5h1t').
swear('5hit').
swear('a55').
swear('anal').
swear('anus').
swear('ar5e').
swear('arrse').
swear('arse').
swear('ass').
swear('ass-fucker').
swear('asses').
swear('assfucker').
swear('assfukka').
swear('asshole').
swear('assholes').
swear('asswhole').
swear('a_s_s').
swear('b!tch').
swear('b00bs').
swear('b17ch').
swear('b1tch').
swear('ballbag').
swear('balls').
swear('ballsack').
swear('bastard').
swear('beastial').
swear('beastiality').
swear('bellend').
swear('bestial').
swear('bestiality').
swear('bi+ch').
swear('biatch').
swear('bitch').
swear('bitcher').
swear('bitchers').
swear('bitches').
swear('bitchin').
swear('bitching').
swear('bloody').
swear('blow job').
swear('blowjob').
swear('blowjobs').
swear('boiolas').
swear('bollock').
swear('bollok').
swear('boner').
swear('boob').
swear('boobs').
swear('booobs').
swear('boooobs').
swear('booooobs').
swear('booooooobs').
swear('breasts').
swear('buceta').
swear('bugger').
swear('bum').
swear('bunny fucker').
swear('butt').
swear('butthole').
swear('buttmuch').
swear('buttplug').
swear('c0ck').
swear('c0cksucker').
swear('carpet muncher').
swear('cawk').
swear('chink').
swear('cipa').
swear('cl1t').
swear('clit').
swear('clitoris').
swear('clits').
swear('cnut').
swear('cock').
swear('cock-sucker').
swear('cockface').
swear('cockhead').
swear('cockmunch').
swear('cockmuncher').
swear('cocks').
swear('cocksuck').
swear('cocksucked').
swear('cocksucker').
swear('cocksucking').
swear('cocksucks').
swear('cocksuka').
swear('cocksukka').
swear('cok').
swear('cokmuncher').
swear('coksucka').
swear('coon').
swear('cox').
swear('crap').
swear('cum').
swear('cummer').
swear('cumming').
swear('cums').
swear('cumshot').
swear('cunilingus').
swear('cunillingus').
swear('cunnilingus').
swear('cunt').
swear('cuntlick').
swear('cuntlicker').
swear('cuntlicking').
swear('cunts').
swear('cyalis').
swear('cyberfuc').
swear('cyberfuck').
swear('cyberfucked').
swear('cyberfucker').
swear('cyberfuckers').
swear('cyberfucking').
swear('d1ck').
swear('damn').
swear('dick').
swear('dickhead').
swear('dildo').
swear('dildos').
swear('dink').
swear('dinks').
swear('dirsa').
swear('dlck').
swear('dog-fucker').
swear('doggin').
swear('dogging').
swear('donkeyribber').
swear('doosh').
swear('duche').
swear('dyke').
swear('ejaculate').
swear('ejaculated').
swear('ejaculates').
swear('ejaculating').
swear('ejaculatings').
swear('ejaculation').
swear('ejakulate').
swear('f u c k').
swear('f u c k e r').
swear('f4nny').
swear('fag').
swear('fagging').
swear('faggitt').
swear('faggot').
swear('faggs').
swear('fagot').
swear('fagots').
swear('fags').
swear('fanny').
swear('fannyflaps').
swear('fannyfucker').
swear('fanyy').
swear('fatass').
swear('fcuk').
swear('fcuker').
swear('fcuking').
swear('feck').
swear('fecker').
swear('felching').
swear('fellate').
swear('fellatio').
swear('fingerfuck').
swear('fingerfucked').
swear('fingerfucker').
swear('fingerfuckers').
swear('fingerfucking').
swear('fingerfucks').
swear('fistfuck').
swear('fistfucked').
swear('fistfucker').
swear('fistfuckers').
swear('fistfucking').
swear('fistfuckings').
swear('fistfucks').
swear('flange').
swear('fook').
swear('fooker').
swear('fuck').
swear('fucka').
swear('fucked').
swear('fucker').
swear('fuckers').
swear('fuckhead').
swear('fuckheads').
swear('fuckin').
swear('fucking').
swear('fuckings').
swear('fuckingshitmotherfucker').
swear('fuckme').
swear('fucks').
swear('fuckwhit').
swear('fuckwit').
swear('fudge packer').
swear('fudgepacker').
swear('fuk').
swear('fuker').
swear('fukker').
swear('fukkin').
swear('fuks').
swear('fukwhit').
swear('fukwit').
swear('fux').
swear('fux0r').
swear('f_u_c_k').
swear('gangbang').
swear('gangbanged').
swear('gangbangs').
swear('gaylord').
swear('gaysex').
swear('goatse').
swear('God').
swear('god-dam').
swear('god-damned').
swear('goddamn').
swear('goddamned').
swear('hardcoresex').
swear('hell').
swear('heshe').
swear('hoar').
swear('hoare').
swear('hoer').
swear('homo').
swear('hore').
swear('horniest').
swear('horny').
swear('hotsex').
swear('jack-off').
swear('jackoff').
swear('jap').
swear('jerk-off').
swear('jism').
swear('jiz').
swear('jizm').
swear('jizz').
swear('kawk').
swear('knob').
swear('knobead').
swear('knobed').
swear('knobend').
swear('knobhead').
swear('knobjocky').
swear('knobjokey').
swear('kock').
swear('kondum').
swear('kondums').
swear('kum').
swear('kummer').
swear('kumming').
swear('kums').
swear('kunilingus').
swear('l3i+ch').
swear('l3itch').
swear('labia').
swear('lmfao').
swear('lust').
swear('lusting').
swear('m0f0').
swear('m0fo').
swear('m45terbate').
swear('ma5terb8').
swear('ma5terbate').
swear('masochist').
swear('master-bate').
swear('masterb8').
swear('masterbat*').
swear('masterbat3').
swear('masterbate').
swear('masterbation').
swear('masterbations').
swear('masturbate').
swear('mo-fo').
swear('mof0').
swear('mofo').
swear('mothafuck').
swear('mothafucka').
swear('mothafuckas').
swear('mothafuckaz').
swear('mothafucked').
swear('mothafucker').
swear('mothafuckers').
swear('mothafuckin').
swear('mothafucking').
swear('mothafuckings').
swear('mothafucks').
swear('mother fucker').
swear('motherfuck').
swear('motherfucked').
swear('motherfucker').
swear('motherfuckers').
swear('motherfuckin').
swear('motherfucking').
swear('motherfuckings').
swear('motherfuckka').
swear('motherfucks').
swear('muff').
swear('mutha').
swear('muthafecker').
swear('muthafuckker').
swear('muther').
swear('mutherfucker').
swear('n1gga').
swear('n1gger').
swear('nazi').
swear('nigg3r').
swear('nigg4h').
swear('nigga').
swear('niggah').
swear('niggas').
swear('niggaz').
swear('nigger').
swear('niggers').
swear('nob').
swear('nob jokey').
swear('nobhead').
swear('nobjocky').
swear('nobjokey').
swear('numbnuts').
swear('nutsack').
swear('orgasim').
swear('orgasims').
swear('orgasm').
swear('orgasms').
swear('p0rn').
swear('pawn').
swear('pecker').
swear('penis').
swear('penisfucker').
swear('phonesex').
swear('phuck').
swear('phuk').
swear('phuked').
swear('phuking').
swear('phukked').
swear('phukking').
swear('phuks').
swear('phuq').
swear('pigfucker').
swear('pimpis').
swear('piss').
swear('pissed').
swear('pisser').
swear('pissers').
swear('pisses').
swear('pissflaps').
swear('pissin').
swear('pissing').
swear('pissoff').
swear('poop').
swear('porn').
swear('porno').
swear('pornography').
swear('pornos').
swear('prick').
swear('pricks').
swear('pron').
swear('pube').
swear('pusse').
swear('pussi').
swear('pussies').
swear('pussy').
swear('pussys').
swear('rectum').
swear('retard').
swear('rimjaw').
swear('rimming').
swear('s hit').
swear('s.o.b.').
swear('sadist').
swear('schlong').
swear('screwing').
swear('scroat').
swear('scrote').
swear('scrotum').
swear('semen').
swear('sex').
swear('sh!+').
swear('sh!t').
swear('sh1t').
swear('shag').
swear('shagger').
swear('shaggin').
swear('shagging').
swear('shemale').
swear('shi+').
swear('shit').
swear('shitdick').
swear('shite').
swear('shited').
swear('shitey').
swear('shitfuck').
swear('shitfull').
swear('shithead').
swear('shiting').
swear('shitings').
swear('shits').
swear('shitted').
swear('shitter').
swear('shitters').
swear('shitting').
swear('shittings').
swear('shitty').
swear('skank').
swear('slut').
swear('sluts').
swear('smegma').
swear('smut').
swear('snatch').
swear('son-of-a-bitch').
swear('spac').
swear('spunk').
swear('s_h_i_t').
swear('t1tt1e5').
swear('t1tties').
swear('teets').
swear('teez').
swear('testical').
swear('testicle').
swear('tit').
swear('titfuck').
swear('tits').
swear('titt').
swear('tittie5').
swear('tittiefucker').
swear('titties').
swear('tittyfuck').
swear('tittywank').
swear('titwank').
swear('tosser').
swear('turd').
swear('tw4t').
swear('twat').
swear('twathead').
swear('twatty').
swear('twunt').
swear('twunter').
swear('v14gra').
swear('v1gra').
swear('vagina').
swear('viagra').
swear('vulva').
swear('w00se').
swear('wang').
swear('wank').
swear('wanker').
swear('wanky').
swear('whoar').
swear('whore').
swear('willies').
swear('willy').
swear('xrated').
swear('xxx').

is_dirty(X) :- swear(X); is_dirty_perm(X).

is_dirty_perm(P) :- atom_chars(P,L), append(A,_,L), length(A,N), N>2, swear(S), atom_chars(S,C), append(_,C,A).
